# Color
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
LIGHTGREY = (100, 100, 100)

# Screen edit
WIDTH_SCREEN = 700
HEIGHT_SCREEN = 700
FPS = 60
TITLE = "Tic Tac Toe"
BACKGROUND_COLOUR = BLACK

# Tile Edit
TILE_AREA = 120
SHINGLE_DIVISION = 3


MARGIN_X = int((WIDTH_SCREEN - (SHINGLE_DIVISION * TILE_AREA)) /2)
MARGIN_Y = int((HEIGHT_SCREEN - (SHINGLE_DIVISION * TILE_AREA)) /2)

def shingleToPixel(x, y) :
    return MARGIN_X + TILE_AREA * x, MARGIN_Y + TILE_AREA * y
